from src.generated import compute_pb2

_SPICE_PREFIX = {
    "resistor": "R",
    "capacitor": "C",
    "inductor": "L",
    "diode": "D",
    "transistor": "Q",
    "ic": "X",
    "voltage_source": "V",
    "current_source": "I",
}

_SPICE_MODEL_HINT = {
    "diode": ".MODEL D_DEFAULT D",
    "transistor": ".MODEL Q_DEFAULT NPN",
}

_IGNORE_TYPES = {"connector"}


def generate_netlist(request: compute_pb2.NetlistRequest) -> compute_pb2.NetlistResponse:
    components = list(request.components)
    nets = list(request.nets)
    warnings: list[str] = []

    if not components:
        return compute_pb2.NetlistResponse(
            netlist="* No components in project", warnings=["no components found"]
        )

    pin_to_net: dict[tuple[str, str], str] = {}
    for net in nets:
        for node in net.nodes:
            pin_to_net[(node.component, node.pin)] = net.name

    net_to_node: dict[str, int] = {}
    _next_node = 1

    def _node_number(net_name: str) -> int:
        nonlocal _next_node
        if net_name.upper() in ("GND", "0"):
            return 0
        if net_name not in net_to_node:
            net_to_node[net_name] = _next_node
            _next_node += 1
        return net_to_node[net_name]

    lines = ["* SPICE netlist generated by HardwarePilot"]
    models_needed: set[str] = set()
    component_count = 0

    for comp in components:
        ctype = comp.type.lower().strip()
        if ctype in _IGNORE_TYPES:
            continue
        prefix = _SPICE_PREFIX.get(ctype)
        if prefix is None:
            warnings.append(f"unknown component type '{comp.type}' for {comp.refdes}, skipping")
            continue

        pins = list(comp.pins)
        if not pins:
            warnings.append(f"no pins defined for {comp.refdes}, skipping")
            continue

        if ctype in ("diode", "transistor"):
            models_needed.add(ctype)

        if ctype in ("resistor", "capacitor", "inductor", "diode"):
            node_names = []
            for pin in pins:
                net_name = pin_to_net.get((comp.refdes, pin.name), "NC")
                node_names.append(str(_node_number(net_name)))
            if len(node_names) < 2:
                node_names.append("0")
            value = comp.value or "1k"
            lines.append(f"{prefix}{comp.refdes} {' '.join(node_names[:2])} {value}")
            component_count += 1

        elif ctype == "transistor":
            collector = "0"
            base = "0"
            emitter = "0"
            for pin in pins:
                net_name = pin_to_net.get((comp.refdes, pin.name), "GND")
                node = str(_node_number(net_name))
                pname = pin.name.lower()
                if "collector" in pname or pname == "c":
                    collector = node
                elif "base" in pname or pname == "b":
                    base = node
                elif "emitter" in pname or pname == "e":
                    emitter = node
            value = comp.value or "Q_DEFAULT"
            lines.append(f"Q{comp.refdes} {collector} {base} {emitter} {value}")
            component_count += 1

        elif ctype == "voltage_source":
            pos_node = "1"
            neg_node = "0"
            for pin in pins:
                net_name = pin_to_net.get((comp.refdes, pin.name), "GND")
                node = str(_node_number(net_name))
                pname = pin.name.lower()
                if "+" in pname or "pos" in pname or "vcc" in pname:
                    pos_node = node
                elif "-" in pname or "neg" in pname or "gnd" in pname:
                    neg_node = node
            value = comp.value or "5"
            lines.append(f"V{comp.refdes} {pos_node} {neg_node} DC {value}")
            component_count += 1

        elif ctype == "current_source":
            pos_node = "1"
            neg_node = "0"
            for pin in pins:
                net_name = pin_to_net.get((comp.refdes, pin.name), "GND")
                node = str(_node_number(net_name))
                pname = pin.name.lower()
                if "+" in pname or "pos" in pname:
                    pos_node = node
                elif "-" in pname or "neg" in pname:
                    neg_node = node
            value = comp.value or "0.001"
            lines.append(f"I{comp.refdes} {pos_node} {neg_node} DC {value}")
            component_count += 1

        elif ctype == "ic":
            nets_for_pins = []
            for pin in pins:
                net_name = pin_to_net.get((comp.refdes, pin.name), "NC")
                nets_for_pins.append(str(_node_number(net_name)))
            value = comp.value or comp.name
            lines.append(f"X{comp.refdes} {' '.join(nets_for_pins)} {value}")
            component_count += 1

    for mtype in sorted(models_needed):
        hint = _SPICE_MODEL_HINT.get(mtype)
        if hint:
            lines.insert(1, hint)

    if component_count == 0:
        warnings.append("no simulatable components found after processing")

    lines.append(".end")
    netlist = "\n".join(lines)

    return compute_pb2.NetlistResponse(netlist=netlist, warnings=warnings)
