import { db } from "@hardwarepilot/db";
import { tool } from "ai";
import { z } from "zod";

const SPICE_PREFIX: Record<string, string> = {
  resistor: "R",
  capacitor: "C",
  inductor: "L",
  diode: "D",
  transistor: "Q",
  ic: "X",
  voltage_source: "V",
  current_source: "I",
};

const SPICE_MODEL_HINT: Record<string, string> = {
  diode: ".MODEL D_DEFAULT D",
  transistor: ".MODEL Q_DEFAULT NPN",
};

const IGNORE_TYPES = new Set(["connector"]);

function generateSpiceNetlist(
  components: Array<{
    id: string;
    name: string;
    type: string;
    value: string | null;
    pins: Array<{ name: string; number: number }>;
    moduleId: string;
  }>,
  nets: Array<{
    name: string;
    connections: Array<{ componentId: string; pinName: string }>;
  }>,
): { netlist: string; warnings: string[] } {
  const warnings: string[] = [];

  if (components.length === 0) {
    return {
      netlist: "* No components in project",
      warnings: ["no components found"],
    };
  }

  const pinToNet = new Map<string, string>();
  for (const net of nets) {
    for (const conn of net.connections) {
      pinToNet.set(`${conn.componentId}:${conn.pinName}`, net.name);
    }
  }

  const netToNode = new Map<string, number>();
  let nextNode = 1;

  function nodeNumber(netName: string): number {
    if (netName.toUpperCase() === "GND" || netName === "0") return 0;
    if (!netToNode.has(netName)) {
      netToNode.set(netName, nextNode++);
    }
    const node = netToNode.get(netName);
    if (node === undefined) {
      netToNode.set(netName, nextNode++);
      return netToNode.get(netName) ?? 0;
    }
    return node;
  }

  const lines = ["* SPICE netlist generated by HardwarePilot"];
  const modelsNeeded = new Set<string>();
  let componentCount = 0;

  for (const comp of components) {
    const ctype = comp.type.toLowerCase().trim();
    if (IGNORE_TYPES.has(ctype)) continue;
    const prefix = SPICE_PREFIX[ctype];
    if (!prefix) {
      warnings.push(`unknown component type '${comp.type}' for ${comp.name}, skipping`);
      continue;
    }

    const pins = comp.pins as Array<{ name: string; number: number }>;
    if (!pins || pins.length === 0) {
      warnings.push(`no pins defined for ${comp.name}, skipping`);
      continue;
    }

    if (ctype === "diode" || ctype === "transistor") {
      modelsNeeded.add(ctype);
    }

    if (
      ctype === "resistor" ||
      ctype === "capacitor" ||
      ctype === "inductor" ||
      ctype === "diode"
    ) {
      const nodeNames: string[] = [];
      for (const pin of pins) {
        const netName = pinToNet.get(`${comp.id}:${pin.name}`) ?? "NC";
        nodeNames.push(String(nodeNumber(netName)));
      }
      if (nodeNames.length < 2) nodeNames.push("0");
      const value = comp.value || "1k";
      lines.push(
        `${prefix}${comp.name.replace(/\s+/g, "_")} ${nodeNames.slice(0, 2).join(" ")} ${value}`,
      );
      componentCount++;
    } else if (ctype === "transistor") {
      let collector = "0";
      let base = "0";
      let emitter = "0";
      for (const pin of pins) {
        const netName = pinToNet.get(`${comp.id}:${pin.name}`) ?? "GND";
        const node = String(nodeNumber(netName));
        const pname = pin.name.toLowerCase();
        if (pname.includes("collector") || pname === "c") collector = node;
        else if (pname.includes("base") || pname === "b") base = node;
        else if (pname.includes("emitter") || pname === "e") emitter = node;
      }
      const value = comp.value || "Q_DEFAULT";
      lines.push(`Q${comp.name.replace(/\s+/g, "_")} ${collector} ${base} ${emitter} ${value}`);
      componentCount++;
    } else if (ctype === "voltage_source") {
      let posNode = "1";
      let negNode = "0";
      for (const pin of pins) {
        const netName = pinToNet.get(`${comp.id}:${pin.name}`) ?? "GND";
        const node = String(nodeNumber(netName));
        const pname = pin.name.toLowerCase();
        if (pname.includes("+") || pname.includes("pos") || pname.includes("vcc")) posNode = node;
        else if (pname.includes("-") || pname.includes("neg") || pname.includes("gnd"))
          negNode = node;
      }
      const value = comp.value || "5";
      lines.push(`V${comp.name.replace(/\s+/g, "_")} ${posNode} ${negNode} DC ${value}`);
      componentCount++;
    } else if (ctype === "current_source") {
      let posNode = "1";
      let negNode = "0";
      for (const pin of pins) {
        const netName = pinToNet.get(`${comp.id}:${pin.name}`) ?? "GND";
        const node = String(nodeNumber(netName));
        const pname = pin.name.toLowerCase();
        if (pname.includes("+") || pname.includes("pos")) posNode = node;
        else if (pname.includes("-") || pname.includes("neg")) negNode = node;
      }
      const value = comp.value || "0.001";
      lines.push(`I${comp.name.replace(/\s+/g, "_")} ${posNode} ${negNode} DC ${value}`);
      componentCount++;
    } else if (ctype === "ic") {
      const netsForPins: string[] = [];
      for (const pin of pins) {
        const netName = pinToNet.get(`${comp.id}:${pin.name}`) ?? "NC";
        netsForPins.push(String(nodeNumber(netName)));
      }
      const value = comp.value || comp.name;
      lines.push(`X${comp.name.replace(/\s+/g, "_")} ${netsForPins.join(" ")} ${value}`);
      componentCount++;
    }
  }

  for (const mtype of [...modelsNeeded].sort()) {
    const hint = SPICE_MODEL_HINT[mtype];
    if (hint) lines.splice(1, 0, hint);
  }

  if (componentCount === 0) {
    warnings.push("no simulatable components found after processing");
  }

  lines.push(".end");
  return { netlist: lines.join("\n"), warnings };
}

export function createTools(projectId: string) {
  return {
    getProjectState: tool({
      description:
        "Get full project state: all modules with their components, inter-module connections, and design constraints. Use when the user asks to see, view, show, or check the project, or when you need current state before making changes.",
      inputSchema: z.object({}),
      execute: async () => {
        const modules = await db.module.findMany({
          where: { projectId },
          include: { components: true },
        });
        const connections = await db.moduleConnection.findMany({
          where: { projectId },
        });
        const constraints = await db.constraint.findMany({
          where: { projectId },
        });
        return {
          modules: modules.map((m) => ({
            id: m.id,
            name: m.name,
            type: m.type,
            description: m.description,
            ports: m.ports,
            dimension: m.dimension,
            status: m.status,
            componentCount: m.components.length,
            components: m.components.map((c) => ({
              id: c.id,
              name: c.name,
              type: c.type,
              value: c.value,
            })),
          })),
          connections: connections.map((c) => ({
            id: c.id,
            sourceModuleId: c.sourceModuleId,
            targetModuleId: c.targetModuleId,
            sourcePortId: c.sourcePortId,
            targetPortId: c.targetPortId,
            type: c.type,
          })),
          constraints: constraints.map((c) => ({
            id: c.id,
            domain: c.domain,
            rule: c.rule,
            priority: c.priority,
          })),
        };
      },
    }),

    createModule: tool({
      description:
        "Create a new module in the project (e.g. MCU, power supply, sensor block, display driver). Use when the user asks to add or create a module.",
      inputSchema: z.object({
        name: z.string().min(1).max(100).describe("Human-readable module name"),
        type: z
          .enum([
            "power",
            "mcu",
            "sensor",
            "display",
            "battery",
            "connectivity",
            "storage",
            "actuator",
            "custom",
          ])
          .describe("Module functional category"),
        description: z.string().optional().describe("Short purpose statement"),
        ports: z
          .array(
            z.object({
              name: z.string(),
              direction: z.enum(["in", "out", "bidirectional"]),
              protocol: z.string().optional(),
              voltage: z.number().optional(),
            }),
          )
          .optional()
          .describe("External ports/pins exposed by this module"),
        dimension: z
          .object({ w: z.number(), h: z.number(), d: z.number() })
          .optional()
          .describe("Bounding box in millimeters"),
      }),
      execute: async ({ name, type, description, ports, dimension }) => {
        const mod = await db.module.create({
          data: {
            projectId,
            name,
            type,
            description: description ?? null,
            ports: ports ?? [],
            dimension: dimension ?? { w: 20, h: 20, d: 5 },
            status: "proposed",
          },
        });
        return { id: mod.id, name: mod.name, type: mod.type, status: mod.status };
      },
    }),

    createComponent: tool({
      description:
        "Add a component (resistor, capacitor, IC, connector, etc.) to an existing module. Use when the user asks to add a part or component.",
      inputSchema: z.object({
        moduleId: z.string().describe("UUID of the parent module"),
        name: z.string().describe("Component name (e.g. '10k Resistor', 'STM32F103')"),
        type: z
          .enum([
            "resistor",
            "capacitor",
            "inductor",
            "diode",
            "transistor",
            "ic",
            "connector",
            "voltage_source",
            "current_source",
            "other",
          ])
          .describe("Component category"),
        value: z.string().optional().describe("Value like '10k', '100nF'"),
        pins: z
          .array(z.object({ name: z.string(), number: z.number() }))
          .optional()
          .describe("Pinout if known"),
      }),
      execute: async ({ moduleId, name, type, value, pins }) => {
        const comp = await db.component.create({
          data: {
            moduleId,
            name,
            type,
            value: value ?? null,
            pins: pins ?? [],
          },
        });
        return { id: comp.id, name: comp.name, type: comp.type };
      },
    }),

    createNet: tool({
      description:
        "Create an electrical net connecting component pins within a module. Use when wiring up a circuit between components.",
      inputSchema: z.object({
        moduleId: z.string().describe("UUID of the parent module"),
        name: z.string().describe("Net name (e.g. 'NET_VCC', 'I2C_SCL')"),
        connections: z
          .array(
            z.object({
              componentId: z.string().describe("Component UUID"),
              pinName: z.string().describe("Pin name on the component"),
            }),
          )
          .describe("List of component pin connections on this net"),
      }),
      execute: async ({ moduleId, name, connections }) => {
        const net = await db.net.create({
          data: {
            moduleId,
            projectId,
            name,
            connections,
          },
        });
        return { id: net.id, name: net.name };
      },
    }),

    addConstraint: tool({
      description:
        "Add a design constraint (mechanical, electrical, manufacturing, or assembly). Use when the user specifies a requirement, limit, or rule the design must satisfy.",
      inputSchema: z.object({
        moduleId: z
          .string()
          .optional()
          .describe("UUID of the module this constraint applies to, if scoped"),
        domain: z
          .enum(["mechanical", "electrical", "manufacturing", "assembly"])
          .describe("Constraint domain"),
        rule: z.string().min(1).max(500).describe("Human-readable rule statement"),
        priority: z
          .enum(["must", "should", "may"])
          .default("should")
          .describe("Priority level: must=hard, should=soft, may=optional"),
      }),
      execute: async ({ moduleId, domain, rule, priority }) => {
        const c = await db.constraint.create({
          data: {
            projectId,
            moduleId: moduleId ?? null,
            domain,
            rule,
            priority,
          },
        });
        return { id: c.id, domain: c.domain, rule: c.rule, priority: c.priority };
      },
    }),

    generateNetlist: tool({
      description:
        "Generate a proper SPICE netlist from all components and nets in the project. Returns valid SPICE syntax with node numbers mapped from net connections. Use when the user asks for a netlist, SPICE export, circuit simulation, or wants to verify circuit topology.",
      inputSchema: z.object({
        analysis: z
          .enum(["dc", "tran", "ac"])
          .optional()
          .default("dc")
          .describe("Analysis type for the simulation (default: dc operating point)"),
      }),
      execute: async ({ analysis }) => {
        const components = await db.component.findMany({
          where: { module: { projectId } },
        });
        const nets = await db.net.findMany({
          where: { projectId },
        });

        const formattedNets = nets.map((n) => ({
          name: n.name,
          connections:
            (n.connections as unknown as { componentId: string; pinName: string }[]) ?? [],
        }));

        const formattedComps = components.map((c) => ({
          id: c.id,
          name: c.name,
          type: c.type,
          value: c.value as string | null,
          pins: c.pins as unknown as { name: string; number: number }[],
          moduleId: c.moduleId,
        }));

        const result = generateSpiceNetlist(formattedComps, formattedNets);

        let header = "";
        if (analysis === "dc") {
          header = ".control\nop\n.endc\n";
        } else if (analysis === "tran") {
          header = ".control\ntran 0.1m 10m\nplot v(1)\n.endc\n";
        } else if (analysis === "ac") {
          header = ".control\nac dec 10 1 1e6\nplot vdb(1)\n.endc\n";
        }

        const fullNetlist = result.netlist.startsWith("*")
          ? header + result.netlist
          : header + result.netlist;

        return {
          netlist: fullNetlist,
          componentCount: components.length,
          netCount: nets.length,
          analysis,
          warnings: result.warnings,
        };
      },
    }),

    simulateCircuit: tool({
      description:
        "Run a DC operating point simulation on the circuit in this project. Generates SPICE netlist from components/nets, runs DC analysis, returns node voltages and currents. Use when the user asks to simulate, test, verify, or check the circuit.",
      inputSchema: z.object({}),
      execute: async () => {
        const components = await db.component.findMany({
          where: { module: { projectId } },
        });
        const nets = await db.net.findMany({
          where: { projectId },
        });

        const formattedNets = nets.map((n) => ({
          name: n.name,
          connections:
            (n.connections as unknown as { componentId: string; pinName: string }[]) ?? [],
        }));

        const formattedComps = components.map((c) => ({
          id: c.id,
          name: c.name,
          type: c.type,
          value: c.value as string | null,
          pins: c.pins as unknown as { name: string; number: number }[],
          moduleId: c.moduleId,
        }));

        const { netlist: rawNetlist, warnings } = generateSpiceNetlist(
          formattedComps,
          formattedNets,
        );

        if (rawNetlist.startsWith("* No components")) {
          return {
            success: false,
            error: "No components to simulate",
            netlist: rawNetlist,
            warnings,
          };
        }

        const fullNetlist = `.control\nop\n.endc\n${rawNetlist}`;

        const computeUrl = process.env.COMPUTE_SERVICE_URL;
        if (computeUrl) {
          try {
            const res = await fetch(`${computeUrl}/simulate`, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                project_id: projectId,
                netlist: fullNetlist,
                analysis_type: "dc",
              }),
              signal: AbortSignal.timeout(15000),
            });
            if (res.ok) {
              const data = await res.json();
              return {
                success: data.success ?? true,
                netlist: fullNetlist,
                signals: data.signals ?? [],
                warnings,
                source: "compute_service",
              };
            }
          } catch {
            // fall through to local MNA solver
          }
        }

        const mnaResult = solveMNA(fullNetlist);

        return {
          success: mnaResult.success,
          netlist: fullNetlist,
          nodeVoltages: mnaResult.nodeVoltages ?? [],
          branchCurrents: mnaResult.branchCurrents ?? [],
          error: mnaResult.error,
          warnings,
          source: "local_mna",
        };
      },
    }),
  };
}

// Minimal MNA (Modified Nodal Analysis) DC solver in TypeScript.
// Solves linear circuits: resistors, independent voltage/current sources.
function solveMNA(netlist: string): {
  success: boolean;
  nodeVoltages?: number[];
  branchCurrents?: number[];
  error?: string;
} {
  type Element = {
    type: "R" | "V" | "I";
    name: string;
    n1: number;
    n2: number;
    value: number;
  };

  const elements: Element[] = [];
  for (const line of netlist.split("\n")) {
    const s = line.trim();
    if (s.startsWith("*") || s.startsWith(".")) continue;
    const parts = s.split(/\s+/);
    if (parts.length < 4) continue;
    const prefix = parts[0][0].toUpperCase();
    if (prefix === "R" || prefix === "V" || prefix === "I") {
      try {
        const n1 = parseInt(parts[1], 10);
        const n2 = parseInt(parts[2], 10);
        const rawVal = parts[3];
        const value = parseSpiceValue(rawVal);
        elements.push({ type: prefix as "R" | "V" | "I", name: parts[0], n1, n2, value });
      } catch {
        // skip unparseable
      }
    }
  }

  if (elements.length === 0) {
    return { success: false, error: "No components to simulate in netlist" };
  }

  const maxNode = Math.max(...elements.flatMap((e) => [e.n1, e.n2]));
  if (maxNode === 0) {
    return { success: false, error: "No nodes found (connect circuit to ground node 0)" };
  }

  const n = maxNode;
  const vSources = elements.filter((e) => e.type === "V");
  const size = n + vSources.length;

  const A: number[][] = Array.from({ length: size }, () => Array(size).fill(0));
  const b: number[] = Array(size).fill(0);

  for (const elem of elements) {
    if (elem.type === "R") {
      const g = 1.0 / Math.max(elem.value, 1e-12);
      if (elem.n1 > 0) {
        A[elem.n1 - 1][elem.n1 - 1] += g;
      }
      if (elem.n2 > 0) {
        A[elem.n2 - 1][elem.n2 - 1] += g;
      }
      if (elem.n1 > 0 && elem.n2 > 0) {
        A[elem.n1 - 1][elem.n2 - 1] -= g;
        A[elem.n2 - 1][elem.n1 - 1] -= g;
      }
    } else if (elem.type === "I") {
      if (elem.n1 > 0) b[elem.n1 - 1] -= elem.value;
      if (elem.n2 > 0) b[elem.n2 - 1] += elem.value;
    }
  }

  for (let idx = 0; idx < vSources.length; idx++) {
    const vsrc = vSources[idx];
    const col = n + idx;
    if (vsrc.n1 > 0) {
      A[vsrc.n1 - 1][col] = 1;
      A[col][vsrc.n1 - 1] = 1;
    }
    if (vsrc.n2 > 0) {
      A[vsrc.n2 - 1][col] = -1;
      A[col][vsrc.n2 - 1] = -1;
    }
    b[col] = vsrc.value;
  }

  try {
    const x = solveLinearSystem(A, b);
    const nodeVoltages: number[] = [0];
    for (let i = 0; i < n; i++) {
      nodeVoltages.push(x[i]);
    }
    const branchCurrents: number[] = [];
    for (let idx = 0; idx < vSources.length; idx++) {
      branchCurrents.push(x[n + idx]);
    }
    return { success: true, nodeVoltages, branchCurrents };
  } catch (e) {
    return { success: false, error: `Matrix singular: ${e}` };
  }
}

function parseSpiceValue(val: string): number {
  val = val.toUpperCase().trim();
  const multipliers: Record<string, number> = {
    F: 1e-15,
    P: 1e-12,
    N: 1e-9,
    U: 1e-6,
    M: 1e-3,
    K: 1e3,
    MEG: 1e6,
    G: 1e9,
    T: 1e12,
  };
  const num = parseFloat(val);
  if (!Number.isNaN(num)) return num;
  for (const [suffix, mult] of Object.entries(multipliers)) {
    if (val.endsWith(suffix)) {
      const numPart = parseFloat(val.slice(0, -suffix.length));
      if (!Number.isNaN(numPart)) return numPart * mult;
    }
  }
  const stripped = parseFloat(val.replace(/[VDCA]/g, ""));
  return Number.isNaN(stripped) ? 1.0 : stripped;
}

function solveLinearSystem(A: number[][], b: number[]): number[] {
  const n = A.length;
  const aug = A.map((row, i) => [...row, b[i]]);

  for (let col = 0; col < n; col++) {
    let maxRow = col;
    for (let row = col + 1; row < n; row++) {
      if (Math.abs(aug[row][col]) > Math.abs(aug[maxRow][col])) maxRow = row;
    }
    if (Math.abs(aug[maxRow][col]) < 1e-12) {
      throw new Error("Singular matrix");
    }
    [aug[col], aug[maxRow]] = [aug[maxRow], aug[col]];

    const pivot = aug[col][col];
    for (let j = col; j <= n; j++) aug[col][j] /= pivot;

    for (let row = 0; row < n; row++) {
      if (row === col) continue;
      const factor = aug[row][col];
      for (let j = col; j <= n; j++) aug[row][j] -= factor * aug[col][j];
    }
  }

  return aug.map((row) => row[n]);
}
